services:
  # --- MINIBLOG ---
  miniblog:
    build: ./miniblog
    container_name: miniblog
    networks:
      - proxy-net

  # --- PROXY PRINCIPAL ---
  proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      # Volumen para el archivo de configuración de NGINX
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Volumen para los recursos (Tipos MIME)
      - ./assets:/var/www/html/assets
    networks:
      - proxy-net
    ports:
      - "8080:80"
    depends_on:
      - miniblog

networks:
  proxy-net:
