services:
  # --- 1. KIOSKO (M1) ---
  app-content:
    build: ./m1
    container_name: app-content
    networks:
      - nginx-net

  # --- 2. PROXY PRINCIPAL (M2) ---
  app-proxy:
    build: ./m2
    container_name: app-proxy
    networks:
      - nginx-net
    depends_on:
      - app-content
      - miniblog-web
    ports:
      - "80:80"

  # --- 3. MINIBLOG WEB (Nginx interno) ---
  miniblog-web:
    image: nginx:alpine
    container_name: miniblog-web
    networks:
      - nginx-net
    volumes:
      - ./miniblog/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./miniblog/html:/var/www/html
    depends_on:
      - miniblog-php

  # --- 4. MINIBLOG PHP (Motor) ---
  miniblog-php:
    build:
      context: ./miniblog
    container_name: miniblog-php
    networks:
      - nginx-net
    volumes:
      - ./miniblog/html:/var/www/html

networks:
  nginx-net: