server {
    listen 80;
    server_name localhost;
    
    # En este miniblog, la web pública está en la carpeta /web
    root /var/www/html/web; 
    index index.php;

    # Configuración de la ubicación de los archivos (si no encuentra el archivo o directorio, devuelve 404)
    location / {
        try_files $uri $uri/ =404;
    }

    # Configuración de la página de error 404
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    location ~ \.php$ {
        # Conectamos con el contenedor de PHP (puerto 9000)
        fastcgi_pass miniblog-php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}