# BLOQUE 1: Catch-all
# Este bloque captura CUALQUIER cosa que no sean dominios oficiales.
# Si entran por localhost, 127.0.0.1, o una IP rara, caen aquí.
server {
    listen 80 default_server;
    server_name _; # El guion bajo es un comodín para "sin nombre"
    
    # Directorio base
    root /var/www/html;

    # Archivo de error 404
    error_page 404 /404.html;
    
    # Captura todo lo que no sea un dominio oficial
    location / {
        return 404;
    }

    # Pagina 404 personalizada
    location = /404.html {
        internal;
    }
}

server {
    listen 80;

    server_name miniblog.kioskofernando.es;

    # Configuración de tipos MIME

    # Configuración de la API (JSON)
    location /api/ { # -> localhost:8080/api/
        # alias -> directorio físico de la API
        alias /var/www/html/assets/api/;
        # types -> tipos MIME que se van a servir
        types{
            application/json json;
        }
        # default_type -> tipo MIME por defecto
        default_type application/json;
    }

    # Configuración para MP4
    location /media/ { # -> localhost:8080/media/
        alias /var/www/html/assets/media/; # -> directorio físico
        # types -> tipos MIME que se van a servir
        types {
            video/mp4 mp4;
        }
        # default_type -> tipo MIME por defecto
        default_type video/mp4;
    }

    # En caso de que no se acceda a ninguna de las anteriores
    location / {
        # Redirige al servicio 'miniblog' (Proxy Inverso)
        proxy_pass http://miniblog:80;
        proxy_set_header Host $host;

        # Cabecera personalizada
        add_header X-Proxied-By NGINX-Docker;
    }
}

server {
    listen 80;

    server_name kioskofernando.es;

    location / {
        proxy_pass http://web:80;
        proxy_set_header Host $host;
    }
}
