server {
    listen 80;

    # Configuración de tipos MIME

    # Configuración de la API (JSON)
    location /api/ { # -> localhost:8080/api/
        # alias -> directorio físico de la API
        alias /var/www/html/assets/api/;
        # types -> tipos MIME que se van a servir
        types{
            application/json json;
        }
        # default_type -> tipo MIME por defecto
        default_type application/json;
    }

    # Configuración para MP4
    location /media/ { # -> localhost:8080/media/
        alias /var/www/html/assets/media/; # -> directorio físico
        # types -> tipos MIME que se van a servir
        types {
            video/mp4 mp4;
        }
        # default_type -> tipo MIME por defecto
        default_type video/mp4;
    }

    # En caso de que no se acceda a ninguna de las anteriores
    location / {
        # Redirige al servicio 'miniblog' (Proxy Inverso)
        proxy_pass http://miniblog:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Cabecera personalizada
        add_header X-Proxied-By NGINX-Docker;
    }
}