server {
    # Puerto del proxy
    listen 80;
    server_name localhost;

    # Directorio raíz de la aplicación
    root /usr/share/nginx/html;
    index index.html;

    # Configuración de la ubicación de los archivos (si no encuentra el archivo o directorio, devuelve 404)
    location / {
        try_files $uri $uri/ =404;
    }

    # Configuración de la página de error 404
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}