# Nuestros dominios correctos

# Kioskofernando
server {
    listen 80;
    # Solo funciona si se accede por el dominio correcto
    server_name kioskofernando.es; 

    location / {
        proxy_pass http://app-content;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        add_header X-Proxy-By Proxy_inverso;
    }
}

# MiniBlog
server {
    listen 80;
    server_name blog.kioskofernando.es;

    location / {
        # Redirigimos al Nginx interno del blog
        proxy_pass http://miniblog-web;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        add_header X-Proxy-By Proxy_inverso;
    }
}

# Para dominios desconocidos
server {
    listen 80 default_server;
    server_name _;
    
    # Captura de errores 404
    error_page 404 /404.html;

    # Ruta del archivo 404.html
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

    # Devuelve un error 404 para todas las peticiones
    location / {
        return 404;
    }

}
